name: Dist CI

on:
  push:
    branches: [ master, franziskus/dist-ci ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  dist-ci-nix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Run CI script
        run: .ci/script.sh

  dist-ci-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run CI script
        run: .ci/script.bat
