name: merge hints and dist

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  merge-hints-and-dist:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: merge
        run: |
          git merge --ff-only origin/build-products-master
      - name: push
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
